---
title: "Dogs and Cats Lovers"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(ggplot2)
library(urbnmapr)

## Reading d
data <- read_csv("cats_vs_dogs.csv")
data$DogstoCatsRation <- data$dog_population/data$cat_population
data$CatstoDogsRation <- data$cat_population/data$dog_population
data$DogsOrCats <- ifelse(data$DogstoCatsRation>0, "LovesDogs", "LovesCats")

```

Row {data-height=650}
-----------------------------------------------------------------------

### Dogs to Cats Ratio

```{r}

data %>%
  left_join(states, by = "state_name") %>%
  ggplot(aes(long, lat, group = group, fill = DogstoCatsRation)) +
  geom_polygon(color = "#ffffff", size = .25) +
  coord_map(projection = "albers", lat0 = 39, lat1 = 45) +
  labs(fill = "Dogs to Cats Ratio") +
  theme(panel.grid = element_blank(),
        axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.background = element_blank()) +
  scale_fill_viridis()

```


### Top 10 Dog loving states

```{r}

data %>%
  group_by(state_name) %>%
  arrange(desc(DogstoCatsRation)) %>%
  head(10) %>%
  ggplot(aes(x = reorder(state_name, -DogstoCatsRation), y = DogstoCatsRation, fill = DogstoCatsRation)) +
  geom_bar(stat = "identity") +
  theme(panel.grid = element_blank(),
        panel.background = element_blank(),
        legend.position = "none") +
  scale_fill_viridis_c() +
  labs(x = "State Name", y = "Dogs to Cats Ratio")

```


Row {data-height=350}
-----------------------------------------------------------------------

### Cats to Dogs Ratio

```{r}

data %>%
  left_join(states, by = "state_name") %>%
  ggplot(aes(long, lat, group = group, fill = CatstoDogsRation)) +
  geom_polygon(color = "#ffffff", size = .25) +
  coord_map(projection = "albers", lat0 = 39, lat1 = 45) +
  labs(fill = "Cats to Dogs Ratio") +
  theme(panel.grid = element_blank(),
        axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.background = element_blank()) +
  scale_fill_viridis()


```

### Top 10 Cat loving states

```{r}

data %>%
  group_by(state_name) %>%
  arrange(desc(CatstoDogsRation)) %>%
  head(10) %>%
  ggplot(aes(x = reorder(state_name, -CatstoDogsRation), y = CatstoDogsRation, fill = CatstoDogsRation)) +
  geom_bar(stat = "identity") +
  theme(panel.grid = element_blank(),
        panel.background = element_blank(),
        legend.position = "none") +
  scale_fill_viridis_c() +
  labs(x = "State Name", y = "Cats to Dogs Ratio")

```

